---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
- name: ubuntu-13.10
- name: ubuntu-12.04
- name: debian-7.2.0
- name: debian-6.0.8
- name: centos-6.5
- name: centos-5.10

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[motd::default]
