LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: ruby19

CaseIndentation:
  IndentWhenRelativeTo: end

MethodLength:
  Max: 50

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false

Style/TrailingComma:
  # If EnforcedStyleForMultiline is comma, the cop allows a comma after the
  # # last item of a list, but only for lists where each item is on its own line.
  EnforcedStyleForMultiline: comma
